---
- name: Create samba docker container
  community.docker.docker_container:
    state: started
    container_default_behavior: no_defaults
    name: samba
    image: dperson/samba
    command: -s "public;/public"
    restart_policy: unless-stopped
    env:
      TZ: "{{ samba_timezone }}"
      WORKGROUP: "{{ samba_workgroup }}"
      USERID: "{{ samba_user_id | string }}"
      GROUPID: "{{ samba_group_id | string }}"
    ports:
      - 139:139
      - 445:445
    volumes:
      - "{{ samba_path }}:/public"
